/*
 * Generated by dtrace(1M).
 */

#ifndef	_STRUC_PROVIDER_H
#define	_STRUC_PROVIDER_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#if _DTRACE_VERSION

#define	STRUC_ADD_BEGIN(arg0, arg1, arg2) \
	__dtrace_struc___add_begin(arg0, arg1, arg2)
#ifndef	__sparc
#define	STRUC_ADD_BEGIN_ENABLED() \
	__dtraceenabled_struc___add_begin()
#else
#define	STRUC_ADD_BEGIN_ENABLED() \
	__dtraceenabled_struc___add_begin(0)
#endif
#define	STRUC_ADD_END(arg0) \
	__dtrace_struc___add_end(arg0)
#ifndef	__sparc
#define	STRUC_ADD_END_ENABLED() \
	__dtraceenabled_struc___add_end()
#else
#define	STRUC_ADD_END_ENABLED() \
	__dtraceenabled_struc___add_end(0)
#endif


extern void __dtrace_struc___add_begin(void *, uint64_t, uint64_t);
#ifndef	__sparc
extern int __dtraceenabled_struc___add_begin(void);
#else
extern int __dtraceenabled_struc___add_begin(long);
#endif
extern void __dtrace_struc___add_end(int);
#ifndef	__sparc
extern int __dtraceenabled_struc___add_end(void);
#else
extern int __dtraceenabled_struc___add_end(long);
#endif

#else

#define	STRUC_ADD_BEGIN(arg0, arg1, arg2)
#define	STRUC_ADD_BEGIN_ENABLED() (0)
#define	STRUC_ADD_END(arg0)
#define	STRUC_ADD_END_ENABLED() (0)

#endif


#ifdef	__cplusplus
}
#endif

#endif	/* _STRUC_PROVIDER_H */
