#!/bin/ksh
#
# This script generates data about response time, using /tools/add_trace.d (for
# slab lists) and /avl/add_trace.d (for avl trees).
#

#General stats, not needed yet.

rm ../$1/add_stats__$3_$4_$2 2> /dev/null

dtrace -q -b 512m -c "$drv $2 $3 $4" -s $add_all -o ../$1/add_stats_$3_$4_$2
dtrace -q -b 512m -c "$drv $2 $3 $4" -s $add_all -o ../$1/add_stats_$3_$4_$2
dtrace -q -b 512m -c "$drv $2 $3 $4" -s $add_all -o ../$1/add_stats_$3_$4_$2
