#!/bin/ksh
#
#
# arg1 = structure implementation
# arg2 = elements to insert
# arg3 = data type and storage method (intsrt, strord, etc)
# arg4 = input pattern (rand or seqinc)
# arg5 = machine name
#

drv=../../build/drv_gen
rm ../$1/$5_throughput_plus_heap_$3_$4_$2 2> /dev/null

if [[ $1 == "sl" ]]; then
	throughput_plus="../../tools/throughput_plus_heap.d"
else 
	throughput_plus="../../drv/throughput_plus_heap.d"
fi

postproc=../../tools/throughput.awk

echo $1 $2 $3 $4 $5
mkdir ../$1
dtrace -c "$drv $1 $2 $3 $4" -s $throughput_plus -o ../$1/$5_throughput_plus_heap_$3_$4_$2

awk -f $postproc ../$1/$5_throughput_plus_heap_$3_$4_$2 > ../$1/$5_throughput_post_$3_$4_$2
