#!/bin/ksh
#
# This script runs all of the benchmarks and creates all of the plots.
#
# example:
#
#	run_all <num elems> <type of list> <add/rem sequence> 
#
#		types of lists:
#			intsrt (integers sorted)
#			strsrt (string sorted)
#
#
#		add/rem sequence:
#			rand
#			seq
#
#			(both adds and rems are either sequential or random)

source ./impls

cd ..
for i in {0..$nimpls}; do
	pfexec rm -r ${impl[$i]}
done
