#!/bin/ksh
#
# This script runs all of the benchmarks and creates all of the plots.
#
# example:
#
#	run_all <num elems> <type of list> <add/rem sequence> 
#
#		types of lists:
#			intsrt (integers sorted)
#			strsrt (string sorted)
#
#
#		add/rem sequence:
#			rand
#			seq
#
#			(both adds and rems are either sequential or random)

source ./impls
source ./input_sizes
source ./machines

for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13; do
	if [[ $1 == "0" ]]; then
		for j in 0 1 2; do
			./run_all ${impl[$i]} ${in_sz[$j]} intsrt rand ${machine[$1]};
			./run_all ${impl[$i]} ${in_sz[$j]} intsrt seqinc ${machine[$1]};
		done
	elif [[ $1 == "1" ]]; then
		for j in 0 1 2 3 4; do
			./run_all ${impl[$i]} ${in_sz[$j]} intsrt rand ${machine[$1]};
			./run_all ${impl[$i]} ${in_sz[$j]} intsrt seqinc ${machine[$1]};
		done
	fi;
done
