#!/bin/ksh
#
# This script runs all of the benchmarks and creates all of the plots.
#
# example:
#
#	run_all <num elems> <type of list> <add/rem sequence> 
#
#		types of lists:
#			intsrt (integers sorted)
#			strsrt (string sorted)
#
#
#		add/rem sequence:
#			rand
#			seq
#
#			(both adds and rems are either sequential or random)

source ./impls
source ./input_sizes
source ./machines

for i in {0..$nimpls}; do
	if [[ $1 == "0" ]]; then
		./run_all ${impl[$i]} ${in_sz[$1]} intsrt rand ${machine[$1]};
		./run_all ${impl[$i]} ${in_sz[$1]} intsrt seqinc ${machine[$1]};
	elif [[ $1 == "1" ]]; then
		./run_all ${impl[$i]} ${in_sz[$1]} intsrt rand ${machine[$1]};
		./run_all ${impl[$i]} ${in_sz[$1]} intsrt seqinc ${machine[$1]};
	fi;
done
